playbook_name: "cis_1_1_2_1_2_remediation"
backup_dir: "/var/log/ai-playbooks-backup/{{ playbook_name }}"
fs_option: "nodev"
partition: "/tmp"
req_01: "Check if /tmp is a separate partition and nodev option is set in /etc/fstab"
req_02: "Add nodev option to /etc/fstab for /tmp"
req_03: "Remount /tmp partition"
req_04: "Verify live mount options of /tmp"
req_05: "Set final compliance status (cis_result)"
