kernel_module_name: "cramfs"
checkpoint_id: "cis_1_1_1_1"
state_guard_dir: "/usr/local/bin/cis/.cis_state_guard/{{ checkpoint_id }}"
state_guard_flag: "{{ state_guard_dir }}/checkpoint.flag"
config_file: "/etc/modprobe.d/{{ kernel_module_name }}.conf"
audit_tasks_file: "../cis_rhel9_audit_tasks/cis_audit_1_1_1_1.yml"
_script_path: "/tmp/cis_remediate_1_1_1_1.sh"
_rem_req_02: "1. Run the provided remediation script to fix Ensure cramfs kernel module is not available."
_rem_req_03: "2. VERIFY: Run audit check to confirm Ensure cramfs kernel module is not available is properly configured."
_rem_req_04: "3. Store the final remediation result in a variable named 'cis_result' using set_fact."
